### ISSUE TITLE
Air connect stop automatically after 1s

### ISSUE THREAD

**Issue by Gandulf78** [eizedev/AirConnect-Synology#106]
## Describe the bug

Airconnect stop automatically after running 1s. 

## To Reproduce

Steps to reproduce the behavior.
Just start airconnect from DSM dashboard. 

## Logfiles

If applicable, add [logfiles](https://github.com/eizedev/AirConnect-Synology#logfiles) to help understand your problem.
[airconnect.log](https://github.com/eizedev/AirConnect-Synology/files/14781057/airconnect.log)

## Hardware

Device on which you are running AirConnect-Synology):

- Synology NAS or Router model name: `[e.g. ds415+]`
DS220+
- (optional) DSM Version `[e.g. DSM 6.2.3-25426 Update 3]`
DSM 7.2.1-69057 Update 4

## Package

Which package from the [releases](https://github.com/eizedev/AirConnect-Synology/releases) page have you downloaded):

- package name: `[e.g. AirConnect-x86-64-0.2.43.0-20201229.spk or the url]`

AirConnect-dsm7-x86_64-static-1.8.3-20240327.spk

**Comment by eizedev** [comment]
Could you please try the non static version?
x84_64 without static

**Comment by Gandulf78** [comment]
Sorry, same result.

**Comment by eizedev** [comment]
Ok, thanks, will check it tomorrow. Changed 1.8.3 back to pre-release.

**Comment by WiteWulf** [comment]
Same problem here with both packages. 
Nothing very meaningful in the logs, I'm afraid:

`[17:17:21] Starting AirConnect ...
[17:17:21] Linking airconnect configuration to "/volume1/airconnect/airconnect.conf".
[17:17:21] Linking airupnp configuration to "/volume1/airconnect/config.xml".
[17:17:21] Starting airupnp on 192.168.1.13:49154
[17:17:21] AirConnect successfully started on ip "192.168.1.13"!
[17:17:22] Status: airupnp not running!
[17:17:22] Status: airupnp not running!
[17:17:35] Status: airupnp not running!
[17:17:50] Status: airupnp not running!
`

Rolled back to  1.7.0 and it's working fine again

**Comment by Xavantes81** [comment]
@WiteWulf try 1.8.1, works faster than 1.7.0 on my setup: 

https://github.com/eizedev/AirConnect-Synology/files/14075677/AirConnect-Synology-1.8.1.zip

**Comment by eizedev** [comment]
The Easter holidays were a little more complicated than expected. I'm still looking at it. Please stick with 1.7.0 or the zipped 1.8.1 for testing. Thank you

**Comment by eizedev** [comment]
Should now be fixed in the latest release: https://github.com/eizedev/AirConnect-Synology/releases/tag/1.8.3-20240403

thanks to @seiryIsNotABlock @seiry for your help to find the problem and creating the pull request!!
