### ISSUE TITLE
the bin file `airupnp` and `aircast` in `AirConnect-dsm7-x86_64-1.8.3-20240327.spk` are broken

### ISSUE THREAD

**Issue by seiry** [eizedev/AirConnect-Synology#107]
## Describe the bug
I downloaded the spk from the pre-release, and it won's start after I installed. And with no log.

https://github.com/eizedev/AirConnect-Synology/releases/tag/1.8.3-20240327

I checked the bin file in the dsm, which showed it was not a valid ELF
<img width="489" alt="image" src="https://github.com/eizedev/AirConnect-Synology/assets/4397354/f645d707-e0fe-46bf-94e7-f75e8239ac67">

And I unpacked the spk file `AirConnect-dsm7-x86_64-1.8.3-20240327.spk` in mac.

<img width="698" alt="image" src="https://github.com/eizedev/AirConnect-Synology/assets/4397354/8ac3da0f-dcde-4a6d-bbf1-a1f066a99fcc">

<img width="655" alt="image" src="https://github.com/eizedev/AirConnect-Synology/assets/4397354/f8b20d8a-8eda-4de0-b4d8-63098db22781">

both of the 2 files are not valid ELF bins.

## other context

to compare, the bin file in https://github.com/eizedev/AirConnect-Synology/releases/tag/1.7.0-20240115 and https://github.com/eizedev/AirConnect-Synology/issues/106#issuecomment-2025906719 is good.

<img width="680" alt="image" src="https://github.com/eizedev/AirConnect-Synology/assets/4397354/60a6d02a-c2bf-4d3c-a6b5-73753fc8a10a">

<img width="675" alt="image" src="https://github.com/eizedev/AirConnect-Synology/assets/4397354/dced7aca-44ed-4d1c-8401-cab5d68b87ea">

And I checked the artifacts in https://github.com/eizedev/AirConnect-Synology/actions/runs/8448579672 , I think there may be something wrong in the action pipeline.

## Package

https://github.com/eizedev/AirConnect-Synology/releases/tag/1.8.3-20240327

- package name: `AirConnect-dsm7-x86_64-1.8.3-20240327.spk`

**Comment by eizedev** [comment]
Thanks @seiry, some other users also realized this.  I need to find a few minutes to investigate the problem.  
There may be two problems, one in the detection in the start-stop-status (src/dsm7/scripts subfolder) script and one in the binary itself, as you suspect.
Therefore i changed it to pre-release until i investigated it.(Only a "problem" due to time (Easter etc.))

**Comment by seiry** [comment]
oh hey @eizedev , I did some research and It's release-downloader broke the extract files.
downgrade it to robinraju/release-downloader@v1.8 would fix.
https://github.com/robinraju/release-downloader/issues/689

And thank you for your cool work! lol

**Comment by eizedev** [comment]
Really cool find! Thanks @seiry 
Would you like to open a pull request? Then i can merge it and you will be named as contributor. if not, i will just "install" the fix later on that day (robinraju/release-downloader@v1.8)

**Comment by seiry** [comment]
yeah, I've already opened one.
https://github.com/eizedev/AirConnect-Synology/pull/108
Also, I enhanced the publish flow. Now when publish a tag, will trigger the build pipeline, and then add the spks to the release.
@eizedev
