### ISSUE TITLE
Is there a version suitable for DSM 7.2.1?

### ISSUE THREAD

**Issue by spen1010** [eizedev/AirConnect-Synology#118]
Hello
I upgraded my DS1821+ from DSM 6.2 to 7.21 (69057 update 5)

I've tried downloade all of the version 1.83 from
[https://github.com/eizedev/AirConnect-Synology/releases](url)
 
and install manually in Package Center. All show version incompatibility
(The old version of Airplay app has been deleted)

Is there a version suitable for DSM 7.2.1?

Thanks

**Comment by eizedev** [comment]
The most current version should work on your device.

Did you uninstall and reinstall the package after the upgrade from 6.x to 7.x?

See readme for Upgrade details.

**Comment by spen1010** [comment]
> The most current version should work on your device.
> 
> Did you uninstall and reinstall the package after the upgrade from 6.x to 7.x?
> 
> See readme for Upgrade details: https://github.com/eizedev/AirConnect-Synology#upgrade-from-dsm6-to-dsm7
> 
> If uninstallation and new install will not work, could you please show details from the log file?

Thank you for your reply

I think I'm lost on the web site. I didn't see the x86_64 version of the file in version 1.83.
I tried to find the previous version but could not find the file download location at the first time.
I tried again today and finally found the x86_64 version of spk in version 1.7.
It works well now. Thank you.

**Comment by eizedev** [comment]
1.8.3 Version for architecture x86-64 is there: 

https://github.com/eizedev/AirConnect-Synology/releases/download/1.8.3-20240403/AirConnect-dsm7-x86_64-1.8.3-20240403.spk

**Comment by spen1010** [comment]
Thanks
I took another look at the content of version 1.83
I think I missed this item to expand on other content.
![5](https://github.com/eizedev/AirConnect-Synology/assets/172875720/f7af235b-f3c6-4b27-9790-2828e19accea)

Thanks again for your reply
