### ISSUE TITLE
Cannot install Airconnect on my Synology NAS DS720+

### ISSUE THREAD

**Issue by Ped68** [eizedev/AirConnect-Synology#121]
## Is your question related to a problem? Please describe
I tried to install Airconnect on my Synology NAS DS720+ (DSM-Version: 7.2.1-69057) with the following packages:

First, I tried: AirConnect-dsm7-x86_64-static-1.7.0-20240115.spk
Second, I tried: AirConnect-dsm7-x86_64-static-1.7.0-20240115.spk

I installed it with manual installation in the paket-manager

At the end of both installation-attempts a window was shown with "Airconnect konnte nicht installiert werden"

The AirConnect application logfile shows: (you find the complete logfile as an attachment):

2024/07/10 15:24:48	start AirConnect 1.7.0-20240115 Begin start-stop-status start
2024/07/10 15:24:48	start AirConnect 1.7.0-20240115 End start-stop-status start ret=[0]

The AirConnect Service logfile shows: (you find the complete logfile as an attachment) shows the same.

What can I do?

Thank you  for your support.

Regards,

Peter
[AirConnect-Application-Logfile.log](https://github.com/user-attachments/files/16163782/AirConnect-Application-Logfile.log)

A clear and concise description of what the problem is. Ex. I'm always frustrated when `[...]`

## Additional context

[AirConnect-Application-Logfile.log](https://github.com/user-attachments/files/16163789/AirConnect-Application-Logfile.log)
[AirConnect-Service-Log-File.log](https://github.com/user-attachments/files/16163796/AirConnect-Service-Log-File.log)

**Comment by eizedev** [comment]
Could you please try the newest non static version?

https://github.com/eizedev/AirConnect-Synology/releases/download/1.8.3-20240403/AirConnect-dsm7-x86_64-1.8.3-20240403.spk

**Comment by Ped68** [comment]
Thank you for your answer.
I tried to install version 1.8.3
Now the error message is:
"Das Paket konnte nicht installiert werden. Freigegebener Ordner mit dme Namen "airconnect" kann nicht erstellt werden."
What can I do?

**Comment by Ped68** [comment]
![2024-07-11_11h06_45](https://github.com/eizedev/AirConnect-Synology/assets/98969971/309f8904-93d1-45df-8d06-6dd9da98c50d)

**Comment by Ped68** [comment]
Please, can you help me?

**Comment by eizedev** [comment]
sorry for the late reply @Ped68 

Have you ever run an old version of AirConnect? Possibly also under DSM 6? The specified error appears when it tries to create the “airconnect” folder (you can find it in File Explorer on your Synology) but it already exists. This can only happen if you are upgrading from a very old version or if AirConnect was previously installed but not uninstalled properly (this was a problem in the early days years years ago).

### Anyway, you can fix this by manually cleanup the old installation

Could you please cleanup your old installation as mentionend in the readme? https://github.com/eizedev/AirConnect-Synology?tab=readme-ov-file#cannot-be-installed-or-upgrade-from-an-older-version

Then please try to reinstall the newest version, this version should work on your device: https://github.com/eizedev/AirConnect-Synology/releases/download/1.8.3-20240403/AirConnect-dsm7-x86_64-1.8.3-20240403.spk

**Comment by Ped68** [comment]
Thank you very much @eizedev 
Today, I tried your solution.
I cleanup my installation as mentioned in the readme.
Then I installed the version AirConnect-dsm7-x86_64-1.8.3-20240403.spk
At the end occurs the error "AirConnect" konnte nicht installiert werden
I post the Logfiles and the screenshots from installation
I have noticed the following - the airconnect directory is not displayed in my FileStation, although it exists
Do you have an idea?

![2024-10-21_20h10_02](https://github.com/user-attachments/assets/7e8f103a-2d11-4502-beff-59f5d8c5ddfc)
![2024-10-21_20h10_52](https://github.com/user-attachments/assets/dde61f8b-ca4e-4009-b3d4-01564460e56c)
![2024-10-21_20h11_19](https://github.com/user-attachments/assets/9384176a-cb4a-4e5a-8991-29a787f52bdb)
[airconnect-2.log](https://github.com/user-attachments/files/17465599/airconnect-2.log)
[airconnect-1.log](https://github.com/user-attachments/files/17465602/airconnect-1.log)
