### ISSUE TITLE
[FEATURE] Own packages only for airupnp or aircast

### ISSUE THREAD

**Issue by eizedev** [eizedev/AirConnect-Synology#14]
The build scripts should be extended or adapted in that individual packages are built only for airupnp or aircast. (i.e. there is one package (airconnect) for both binaries and one package only for airupnp or aircast).

Alternatively, it could be considered to include the Synology Package Manager GUI and to integrate a selection menu during installation (WIZARD_UIFILES folder) which binaries should be installed and managed (Both, airupnp, aircast).

**Comment by eizedev** [comment]
This will be the new selection menu during installation in the package center:

![image](https://user-images.githubusercontent.com/6794362/103991537-16d48180-5193-11eb-8920-d1fb96f3644c.png)

**Comment by Gummibando** [comment]
Awesome :)

**Comment by eizedev** [comment]
The basic integration is as good as finished. I just have to adjust a few small things, then you are very welcome for testing ;)

**Comment by eizedev** [comment]
@Gummibando 

The UI integration for selecting airupnp/aircast (or both) is now integrated in the latest release.
Currently only compatible with DSM 7 and above.

It would be great, if you could test it: [0.2.50.5-20210801](https://github.com/eizedev/AirConnect-Synology/releases/tag/0.2.50.5-20210801)

**Comment by Gummibando** [comment]
This sound fantastic.
Unfortunately, I'm not yet on DSM 7. Still have some data cleanup to do before full system backup and taking the plunge. . Additionally, just two days ago I sent my streamer for servicing, not sure when it will be returned.
Will test as soon as I'm ready.

**Comment by eizedev** [comment]
No problem :) 
I plan to provide this change probably also for DSM 6, that should be relatively quickly achievable :). With future innovations I just have to see to what extent it is still worth it. The basic functionality will of course always remain as long as it is technically possible.

**Comment by Gummibando** [comment]
Sorry for replying late, but I just came back from being very AFZ (away from zuhause :).

![berg](https://user-images.githubusercontent.com/34392542/132130190-31fa8796-ec45-4d1e-b938-53681908d9e0.jpg)

Status so far:

I can install the package and the shared folder is created.
Running the package brings up two error messages, missing IP and UPNP port, respectively.

`AirConnect: [15:20:46] Synology IP cannot be found! Please uninstall the package and reinstall it again! (or change SYNO_IP in "/volume1/@appstore/AirConnect/airconnect.conf")`

`AirConnect: [15:21:54] AIRUPNP port cannot be found! Please uninstall the package and reinstall it again (or set AIRUPNP_PORT in "/volume1/@appstore/AirConnect/airconnect.conf")!`

It runs after manually editing the (automatically created) config file, which, as per the documentation, should only be relevant for DSM 7.
Two empty xml files are created (config.xml, config-cast.xml), meaning the player (a Naim streamer) is not discovered and not available as an AirPlay target.

After running `airupnp -i config.xml`, the config.xml file is populated with data, so it appears the streamer is discovered.
But it is still not available as an AirPlay target. Stopping/restarting the package in Package Center brings no change, the log file looks ok (no obvious errors), though.

A check with a Bonjour browser app (BonJeff) shows no added airplay/raop service broadcast.

**Comment by eizedev** [comment]
Sorry @Gummibando, the bot closed the issue because it was stale ;-) 
Thanks for your detailed report, i will check it in the next days. Do you still use DSM6?

**Comment by Gummibando** [comment]
Exactly. Package running, no devices found. The device is a Naim streamer.
Unfortunately, I have upgraded to DSM 7(.0.1) by now.

**Comment by eizedev** [comment]
Ok, thanks for the info. I have two other issues for the DSM6 packages that i want to implement in the upcoming weeks. I will have a look at it.
For now i will close this issue since the original problem was resolved with DSM7 and you have upgrade to DSM7 now.
