### ISSUE TITLE
Cannot start, Cannot load SSL libraries

### ISSUE THREAD

**Issue by Vinisz** [eizedev/AirConnect-Synology#17]
Hi,

Installed AirConnect-x86-0.2.43.1-20210115.spk on a Synology DS415+ 
However, when trying to start from the GUI, it stops straight away...
When trying to start via SSH, (./airupnp) it gives error: Start:1132 Cannot load SSL libraries
Any idea what's wrong here ?

**Comment by eizedev** [comment]
Hi, on a ds415+ you need to download and install the x86-64 Package.

**Comment by Vinisz** [comment]
Strange, I thought I had the right one.. but works now, thanks !

 

Van: René <notifications@github.com> 
Verzonden: zaterdag 16 januari 2021 14:59
Aan: eizedev/AirConnect-Synology <AirConnect-Synology@noreply.github.com>
CC: Vinisz <vszabang@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [eizedev/AirConnect-Synology] Cannot start, Cannot load SSL libraries (#17)

 

Hi, on a ds415+ you need to download and install the x86-64 Package.
