### ISSUE TITLE
[FEATURE] Add AirConnect Airplay Speaker to Homekit

### ISSUE THREAD

**Issue by emanut** [eizedev/AirConnect-Synology#18]
Is there a way to add the new AirConnect Airplay speakers to a room in Homekit? So I could use Siri to play something in a room.

Thanks
Emanuel

**Comment by eizedev** [comment]
Hi @emanut 

Unfortunately, I am not familiar with HomeKit. I think your request would be better served in the official [AirConnect](https://github.com/philippe44/AirConnect) repository. The community is bigger there. There is a better chance that they can help you.

Please take a look [here](https://github.com/philippe44/AirConnect/issues)
