### ISSUE TITLE
AirConnect package can't start

### ISSUE THREAD

**Issue by leroyrichjr** [eizedev/AirConnect-Synology#3]
I am having a problem where AirConnect fails to start.  Here is a startup/shutdown cycle from the log file.

`[23:56:24] Starting aircast on 172.16.0.11`
`[23:56:24.013382] main:951 Starting aircast version: v0.2.27.0 (Aug  3 2020 @ 11:16:54)`
`[23:56:24.013552] main:959 no config file, using defaults`
`[23:56:24.013942] Start:715 Binding to 172.16.0.11`
`[23:56:24.014271] Start:720 Cannot load SSL libraries`
`[23:56:24.014306] main:992 Cannot start`
`[23:56:24] Searching if renderer were added (for 10 seconds)...`
`[23:56:24.055522] Start:1103 Binding to 172.16.0.11:49154`
`[23:56:24.055836] Start:1108 Cannot load SSL libraries`
`[23:56:24.057442] main:1426 Cannot start`
`[23:56:34] Failed to start AirConnect on ip "172.16.0.11", stopping it...`
`[23:56:34] Stopping AirConnect ...`

This is the error that's visible is the DSM.

<img width="528" alt="Screen Shot 2020-09-02 at 12 07 35 AM" src="https://user-images.githubusercontent.com/10944729/91934205-5b658300-ecb0-11ea-96c0-36426494b3da.png">

Thanks in advance!

**Comment by eizedev** [comment]
Hi @leroyrichjr 

`[23:56:24.014271] Start:720 Cannot load SSL libraries`

What Synology NAS (model) are you using and [what package did you download](https://github.com/eizedev/AirConnect-Synology#download-the-pre-build-synology-package)?

Background of my question is about the ssl Libraries: aircast and airupnp needs these two libraries libcrypt.so and libssl.so. They should be, by default, available on your NAS (LD_LIBRARY_PATH).

**Comment by leroyrichjr** [comment]
It's a DS1817+ and I downloaded AirConnect-x86-0.2.27.0-20200810.spk, which now I realize is the wrong one.  I installed AirConnect-x86-64-0.2.27.0-20200810.spk instead and it works great.  Sorry to be a pain in the butt and thanks for such a great utility.
