### ISSUE TITLE
How to airplay to Synology and use the sound card on Synology to play

### ISSUE THREAD

**Issue by 521tonysteven** [eizedev/AirConnect-Synology#35]
How to airplay to Synology and use the sound card on Synology to play

**Comment by eizedev** [comment]
Can you please explain this a little bit closer?
What is connected to the sound card on your Synology NAS?

With AirConnect you can use airplay to stream your music to speakers that do not natively support AirPlay. These speakers can be Sonos devices, DLNA devices, Chromecast devices but also other devices that are including DLNA/Chromecast techniques.
