### ISSUE TITLE
static version or not?

### ISSUE THREAD

**Issue by W4J1e** [eizedev/AirConnect-Synology#36]
## Is your question related to a problem? Please describe

NO

## Describe the solution you'd like
is static version different to non-static version? I can install both of them and work normally, so can anyone explain what the difference they are? Thank you.

**Comment by eizedev** [comment]
Hi @W4J1e 
The static package includes "static" binaries, that means, it includes binaries that have no external library dependencies and should be run on your device if the "normal" package (without static in the name) fails.
On some devices, dependencies that are necessary to run airupnp or aircast are not available (mostly on older devices).
These dependencies are included in the static version of the package. This is the reason why the static packages are bigger than the normal versions.

So in general always use the normal package, not the static one. Only when the normal package does not work on your device, please test the static package instead.

**Comment by W4J1e** [comment]
@eizedev Ok I got it. thanks  a lot for your answer !
Best Wishes~
