### ISSUE TITLE
Install issue with AirConnect-x86-64-0.2.50.5-20210826

### ISSUE THREAD

**Issue by mvonh** [eizedev/AirConnect-Synology#39]
## Describe the bug

Package installs but fails to run with an error message

<img width="611" alt="Screen Shot 2021-11-05 at 11 08 44 PM" src="https://user-images.githubusercontent.com/25800805/140596201-c9bc530a-d097-437b-9f9d-98febdd34d7c.png">
## To Reproduce
Manuall install from download

## Expected behavior

Should run after install
## Logfiles

If applicable, add [logfiles](https://github.com/eizedev/AirConnect-Synology#logfiles) to help understand your problem.

## Hardware

Device on which you are running AirConnect-Synology):

- Synology NAS  ds415+
- (optional) DSM Version `[e.g. DSM 6.2.4-25556 Update 2]`

## Package

Which package from the [releases](https://github.com/eizedev/AirConnect-Synology/releases) page have you downloaded):

- package name: `AirConnect-x86-64-0.2.50.5-20210826.spk

## Additional context

Do I need to create the config file, or setup some kind of permissions for this to run

**Comment by eizedev** [comment]
Hi @mvonh 

strange, that release that you picked should work for dsm6. Did you uninstalled the package and the tried a fresh installation?

>You could you please try an older version: [0.2.50.5-20210630](https://github.com/eizedev/AirConnect->Synology/releases/tag/0.2.50.5-20210630)
>So for your device, it is the package [AirConnect-x86-64-0.2.50.5-20210630.spk](https://github.com/eizedev/AirConnect->Synology/releases/download/0.2.50.5-20210630/AirConnect-x86-64-0.2.50.5-20210630.spk)

Thanks
