### ISSUE TITLE
can not use in ds916

### ISSUE THREAD

**Issue by waterfish007** [eizedev/AirConnect-Synology#4]
I install the program in GUI successfully,i it doesn't work.
Until I in ssh mode, and input 

cd /volume1/@appstore/AirConnect
./aircast

then, it work!

but, how can I use in ever reboot automatic without ssh a command?

and 

Will support airplay2 in future?

**Comment by eizedev** [comment]
Hi @waterfish007 

This is not normal behavior. In the current version both airupnp and aircast should start automatically without the need to log in via SSH. 

The problem can occur when updating from a (much) older version, because during the update the scripts of the old version are used to uninstall the new version.
Have you ever tried to install it again with the SPK package? This will also use the current scripts, maybe it helps that it is started afterwards.

Otherwise, could you please check (or upload) the logfiles? See https://github.com/eizedev/AirConnect-Synology#logfiles for more information.

For AirPlay2 support, please check the official issues at https://github.com/philippe44/AirConnect/issues?q=is%3Aissue+airplay2 
As far as i know, an airplay2 support is not planned for the future.

**Comment by waterfish007** [comment]
> Hi @waterfish007
> 
> This is not normal behavior. In the current version both airupnp and aircast should start automatically without the need to log in via SSH.
> 
> The problem can occur when updating from a (much) older version, because during the update the scripts of the old version are used to uninstall the new version.
> Have you ever tried to install it again with the SPK package? This will also use the current scripts, maybe it helps that it is started afterwards.
> 
> In your example you just start aircast with the default configuration, normally it will be started with a few more parameters/configuration, see https://github.com/eizedev/AirConnect-Synology#how-it-works for more information.
> 
> Default startup commands (started with user airconnect):
> 
> ```shell
> /volume1/@appstore/AirConnect/airupnp -b [synology device local ip]:49154 -l 1000:2000 -x "/volume1/@appstore/AirConnect/config.xml" -z -f "/var/log/airconnect.log" -d all=info  
> /volume1/@appstore/AirConnect/aircast -b [synology device local ip] -l 1000:2000 -x "/volume1/@appstore/AirConnect/config-cast.xml" -z -f "/var/log/airconnect.log" -d all=info
> ```
> 
> Otherwise, could you please check (or upload) the logfiles? See https://github.com/eizedev/AirConnect-Synology#logfiles for more information.
> 
> For AirPlay2 support, please check the official issues at https://github.com/philippe44/AirConnect/issues?q=is%3Aissue+airplay2
> As far as i know, airplay2 support is not planned for the future.

Thank's for answer, but I found the program works unstable.i don't know is my NAS's problem or anything else.
here is the log.
Thank you again!
[airconnect.log](https://github.com/eizedev/AirConnect-Synology/files/5303527/airconnect.log)

**Comment by eizedev** [comment]
hmm, strange...
In your logfile i see two ip addresses for your NAS system, is this correct? 
-> 192.168.1.111 and 172.30.32.1

At the beginning 192.168.1.111 will be used, later on 172.30.32.1 and the last successful startup i can see is with ip 192.168.1.111.
Do you have your speakers in another subnet as your other devices? How is your network setup? (Router/Firewall etc.)

So in general, the AirConnect Synology package is working, but sometimes it does not recognize any device (Your google Home devices) in the first 10 seconds, so it will stop the program. After it discovers any google home device, it is working. 
At the end you will see the following lines in your logfile:

```log
[20:16:56.657879] MRThread:332 [0x68f3c0]: Cast peer closed connection
[02:57:55.102906] CastPingThread:665 [0x7fe60000abf0]: No response to ping
[02:57:55.163524] read_bytes:169 [s-0x7fe60000b3a0]: socket closed
[02:57:55.163612] CastSocketThread:710 [0x7fe60000abf0]: SSL connection closed
[04:23:25.904343] mDNSsearchCallback:454 [0x68f3c0]: removing renderer (Google Home Max+) 0
[10:01:54] Status: aircast not running!
```

I do not exactly know where this comes from, but it does not have any connection to the speakers anymore and is crashing.

**Comment by waterfish007** [comment]
> hmm, strange...
> In your logfile i see two ip addresses for your NAS system, is this correct?
> -> 192.168.1.111 and 172.30.32.1
> 
> At the beginning 192.168.1.111 will be used, later on 172.30.32.1 and the last successful startup i can see is with ip 192.168.1.111.
> Do you have your speakers in another subnet as your other devices? How is your network setup? (Router/Firewall etc.)
> 
> So in general, the AirConnect Synology package is working, but after Airconnect (airupnp and aircast) starts, sometimes it does not recognize any device (Your google Home devices) in the first 10 seconds, so it will stop the program. After it discovers any google home device, it is working.
> At the end you will see the following lines in your logfile:
> 
> ```
> [20:16:56.657879] MRThread:332 [0x68f3c0]: Cast peer closed connection
> [02:57:55.102906] CastPingThread:665 [0x7fe60000abf0]: No response to ping
> [02:57:55.163524] read_bytes:169 [s-0x7fe60000b3a0]: socket closed
> [02:57:55.163612] CastSocketThread:710 [0x7fe60000abf0]: SSL connection closed
> [04:23:25.904343] mDNSsearchCallback:454 [0x68f3c0]: removing renderer (Google Home Max+) 0
> [10:01:54] Status: aircast not running!
> ```
> 
> I do not exactly know where this comes from, but it does not have any connection to the speakers anymore and is crashing.

Thank you for the reply.I found 172.30.32.1 is the docker of hassio in the DSM system.You guide the solution for me .

**Comment by eizedev** [comment]
Ah, cool :) You are welcome, i will close the issue
