### ISSUE TITLE
it not support huawei sound

### ISSUE THREAD

**Issue by hanzixi** [eizedev/AirConnect-Synology#42]
huawei sound or sound x support DLNA;  DSM install airconnect can not find huawei sound device; xiaomi sound is ok;  can you support it? thank you!

**Comment by eizedev** [comment]
Hi,

it could be possible, that the default configuration does not allow your huawei device.  
You can find more information about how to change the allowed AirPlay devices in the [documentation](https://github.com/eizedev/AirConnect-Synology#supported-upnp-speakers).

In short:

For a first test, you can change the [airconnect.conf](https://github.com/eizedev/AirConnect-Synology#airconnectconf) configuration file and remove the Line `FILTER_AIRPLAY2_DEVICES="<NULL>,S1,S3,S5,S9,S12,ZP80,ZP90,S15,ZP100,ZP120,1.0,LibreWireless"`.
Then save the file and restart the `AirConnect-Synology` package in the package manager gui.

If you remove this line, all speakers that are found on your network should be found by AirConnect.

**Comment by hanzixi** [comment]
Last night I tested 0.2.50.5-20210826 according to your method; modify the configuration as follows:
AIRCAST_ENABLED=1
AIRCAST_LATENCY="1000:2000"
AIRCAST_LOGLEVEL="all=info"
AIRUPNP_ENABLED=1
AIRUPNP_LATENCY="1000:2000"
AIRUPNP_LOGLEVEL="all=info"
AIRUPNP_PORT=49154
FILTER_AIRPLAY2_DEVICES="<NULL>"
SYNO_IP="192.168.31.106"

After I restarted airconnect, I still couldn't find the HuaWei sound device;
I used the ssh tool to connect to my DSM system, and I found aircast and airupnp under the /volume2/@appstore/AirConnect path; I manually executed airupnp, a miracle appeared, and the HuaWei sound device could be found;

![e12449f22414c1b3a824cc2e3af2c50](https://user-images.githubusercontent.com/71420611/143518249-753d6f51-291c-402c-b247-3ed9915e3693.png)

[23:44:04.897900] main:1420 Starting airupnp version: v0.2.50.5 (May 24 2021 @ 15:14:33)
[23:44:04.898040] main:1428 no config file, using defaults
[23:44:04.984282] Start:1130 Binding to 192.168.31.106:49154
[23:44:07.301448] AddMRDevice:1008 [0x7f2fca5d6010]: adding renderer (HUAWEI Sound-00721)
[23:44:07.308601] MasterHandler:669 [0x7f2fca5d6010]: subscribe success
[23:44:07.316544] ProcessEvent:464 [0x7f2fca5d6010]: UPnP Volume local change 46:-1 (master)
[23:44:10.010900] rtsp_thread:347 got RTSP connection 13
[23:44:10.011118] rtsp_thread:362 RTSP close 13
[23:44:53.187196] rtsp_thread:347 got RTSP connection 12
[23:44:53.419715] handle_rtsp:395 [0x7f2fb00018c0]: challenge BKpD4HQN/bIlFT/MGIDoIw==
[23:44:53.535499] handle_rtsp:388 [0x7f2fb00018c0]: received ANNOUNCE
[23:44:53.539208] handle_rtsp:592 [0x7f2fb00018c0]: responding:

Only if I manually execute airupnp to find the device, I still can't find the device automatically after I restart DSM;
When I tried to use the iPhone’s airplay to push music, bad things appeared. I found that my Huawei sound had no sound. I tested the connection and volume adjustment and it was ok, but there was no sound; in addition, it would appear when playing music. There is an automatic stop;

I used the command to grab some logs, but I could not locate the problem, so I sent the log to you, I hope you can help locate and solve the problem; thank you;

In addition, my Synology system is DSM 6.1.7-15284; the model is DS3165xs;



[errlog.log](https://github.com/eizedev/AirConnect-Synology/files/7605978/errlog.log)
[log.log](https://github.com/eizedev/AirConnect-Synology/files/7605987/log.log)
[airconnect.log](https://github.com/eizedev/AirConnect-Synology/files/7605988/airconnect.log)
[airconnect.conf.log](https://github.com/eizedev/AirConnect-Synology/files/7605991/airconnect.conf.log)

**Comment by eizedev** [comment]
Thanks for the details, could you please try to completely remove the configuration Line for `FILTER_AIRPLAY2_DEVICES`? So in your case it should look something like that?

```conf
AIRCAST_ENABLED=1
AIRCAST_LATENCY="1000:2000"
AIRCAST_LOGLEVEL="all=info"
AIRUPNP_ENABLED=1
AIRUPNP_LATENCY="1000:2000"
AIRUPNP_LOGLEVEL="all=info"
AIRUPNP_PORT=49154
SYNO_IP="192.168.31.106"
```

After that, please restart AirConnect-Synology (f.e. via package center). Then you should see your device.

If then, your iphone founds the device but you hear no sound after you select it, this is another issue.  
That could be related to another issue that you can find in the AirConnect repository [here](https://github.com/philippe44/AirConnect/issues/377).

**Comment by hanzixi** [comment]
Yes, I have tested before deleting all the contents of "FILTER_AIRPLAY2_DEVICES="<NULL>,S1,S3,S5,S9,S12,ZP80,ZP90,S15,ZP100,ZP120,1.0,LibreWireless"", but it starts after deleting Failed, prompting that there is no FILTER_AIRPLAY2_DEVICES; later I changed to "FILTER_AIRPLAY2_DEVICES="<NULL>""; I can start, but I still can't find the device;

According to your prompt, I tried to modify the configuration last night, modified to: FILTER_AIRPLAY2_DEVICES=, removed "NULL"; then restarted and found that HuaWei sound can be found; all configurations are as follows:
AIRCAST_ENABLED=1
AIRCAST_LATENCY="1000:2000"
AIRCAST_LOGLEVEL="all=info"
AIRUPNP_ENABLED=1
AIRUPNP_LATENCY="1000:2000"
AIRUPNP_LOGLEVEL="all=info"
AIRUPNP_PORT=49154
FILTER_AIRPLAY2_DEVICES=
SYNO_IP="192.168.31.106"
