### ISSUE TITLE
Add support for Devialet UPnP speaker

### ISSUE THREAD

**Issue by caramdache** [eizedev/AirConnect-Synology#46]
As per the README file, here are the parameters necessary to add support for the Devialet Expert Pro product line:

```
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:2</deviceType>
<friendlyName>Devialet Expert Pro 140</friendlyName>
<manufacturer>Devialet</manufacturer>
<manufacturerURL>https://www.devialet.com</manufacturerURL>
<modelDescription>The ultimate audiophile system</modelDescription>
<modelName>Expert 140 Pro</modelName>
<modelNumber>2.2.6</modelNumber>
<modelURL>https://www.devialet.com/expert-pro-audio-system</modelURL>
```

**Comment by eizedev** [comment]
Hi, thanks for the feedback. I will add the device to the default filter list in the next release.

**Comment by eizedev** [comment]
Hi,

i have added your device to the default filter list in the current release [0.2.51.2-20220130](https://github.com/eizedev/AirConnect-Synology/releases/tag/0.2.51.2-20220130).

Please keep in mind, that if you upgrade your existing AirConnect-Synology package no changes will be made to the airconnect.conf file. If you want to overwrite your airconnect.conf configuration with the default one, please uninstall and install the package again. You can also copy the default values found in the [documentation](https://github.com/eizedev/AirConnect-Synology#airconnectconf). In your example, please add `,2.2.6` to the default list of `FILTER_AIRPLAY2_DEVICES`.

Thanks again for your feedback.

**Comment by caramdache** [comment]
Excellent, thank you!  I can indeed see the devices from my MacBook Pro and play to it.

I will take a little time before I've tested this thoroughly, but already I've seen an issue already: when I play music, if the device was in standby (from an amp POV) but nonetheless visible as a UPnP device, the device disappears and no sounds comes out. I have to wait for the device to reappear and press play again.

I haven't seen this issue with other UPnP controllers.

**Comment by eizedev** [comment]
Great that it worked!

hmm... strange. Have you checked the logfile for possible errors related to your device?
That does not look like an error with the Synology package itself. If the problem persists you can also open an issue in the official repository [here](https://github.com/philippe44/AirConnect/issues)

(You can also post the logfile or parts of the logfile here, then I can have a look at it.)
