### ISSUE TITLE
New Device

### ISSUE THREAD

**Issue by norabor** [eizedev/AirConnect-Synology#47]
Please add this player to the supported list. It's a frontier silicon based internet radio. No native airplay.

<device>
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
<friendlyName>Some Name</friendlyName>
<manufacturer>Adition</manufacturer>
<manufacturerURL>http://www.frontier-silicon.com</manufacturerURL>
<modelDescription>ir-mmi-FS2026-0500-0748_V2.14.19c3.EX73616-1A23</modelDescription>
<modelName>Fitzwilliam</modelName>
<modelNumber>Fitzwilliam</modelNumber>
<modelURL>http://www.frontier-silicon.com</modelURL>
<serialNumber>120a170e33171f270101cc00ffffc9ff</serialNumber>
<UDN>uuid:3DCC7100-F76C-11DD-87AF-0022618C9BEC</UDN>

**Comment by norabor** [comment]
I managed to get the device running by adding "Fitzwilliam" to the filter list in airconnect.conf (extremely hard to do for a non-linux person). Manually adding the device through a config.xml did not work as the filter seems to override even manually added devices. It might make sense to not filter anything in the manual device area of the config.xml

**Comment by eizedev** [comment]
Hi, i will add the device in the next release to the default filter list. 
I will also extend the documentation to clarify that you need to remove the filter list (`FILTER_AIRPLAY2_DEVICES=`) if you add a custom configuration xml file.
Thanks for your feedback.

**Comment by eizedev** [comment]
Hi,

i have added your device to the default filter list in the current release [0.2.51.2-20220130](https://github.com/eizedev/AirConnect-Synology/releases/tag/0.2.51.2-20220130).

Please keep in mind, that if you upgrade your existing AirConnect-Synology package no changes will be made to the airconnect.conf file. If you want to overwrite your airconnect.conf configuration with the default one, please uninstall and install the package again. You can also copy the default values found below to your configuration file.

You could also edit your airconnect.conf file using your windows pc. Connect to your NAS using a fileshare to shared folder airconnect. First you need to make sure you have allowed symlinks for SMB in your synology configuration. If not enabled you will not see airconnect.conf file. I have updated the documentation: [Editing airconnect.conf using your PC](https://github.com/eizedev/AirConnect-Synology#editing-airconnectconf-using-your-pc).

Thanks again for your feedback.
