### ISSUE TITLE
airconnect.conf inaccessible

### ISSUE THREAD

**Issue by norabor** [eizedev/AirConnect-Synology#48]
I'm using the ARM package on DS216j with DSM 7.0.1-42218.

1)
The access rights for airconnect.conf were to only allow read access for all users but "Airconnect". So it was not possible to use the symlink in volume1/airconnect to edit the file via a share. Changing the access rights to e.g. 666 solved this.

2)
SMB on Synology by default doesn't support following symlinks. So the documentation might need a hint to activate this in SMB=>Enhanced Settings=>Others (both options are required)

Now I can edit the configuration with windows.

Thank you for a great package.

**Comment by eizedev** [comment]
Hi,

ah, this is an interesting find. 

i will update the file permissions and the documentation in the next release. Thanks!

**Comment by eizedev** [comment]
Hi, i have updated the clarification in the documentation and fixed the bug with the file permissions in release [0.2.51.2-20220130](https://github.com/eizedev/AirConnect-Synology/releases/tag/0.2.51.2-20220130).
The file permissions will also be fixed (Access: (0666/-rw-rw-rw-)) on upgrading to the new version. Any configuration in `airconnect.conf` will be kept "as it is" on upgrade (i have clarified this in the readme). Therefore you need to uninstall and reinstall the package.

Thanks again for your great feedback!
