### ISSUE TITLE
Please Add Support For Samsung HW-N950

### ISSUE THREAD

**Issue by WiteWulf** [eizedev/AirConnect-Synology#52]
Please add support for Samsung HW-N950 soundbar to airupnp.

I can confirm that airupnp works very well when run manually from command-line without any model name filters, but the model details needs to be added to the Synology package.

Relevant output from upnp announce as follows:

```
    <modelDescription>Samsung SOUNDBAR DMR</modelDescription>
    <modelName>HW-N950</modelName>
    <modelNumber>AllShare1.0</modelNumber>
```

**Comment by eizedev** [comment]
Hi,

i have added your device to the default filter list in the current release [0.2.51.2-20220206](https://github.com/eizedev/AirConnect-Synology/releases/tag/0.2.51.2-20220206).

Please keep in mind, that if you upgrade your existing AirConnect-Synology package no changes will be made to the airconnect.conf file. If you want to overwrite your airconnect.conf configuration with the default one, please uninstall and install the package again. You can also copy the default values found in the [documentation](https://github.com/eizedev/AirConnect-Synology#airconnectconf).

Thanks for your feedback.
