### ISSUE TITLE
how to force the airconnect automatically and always running?

### ISSUE THREAD

**Issue by ycj1989** [eizedev/AirConnect-Synology#54]
halo eizedev,
I have installed airconnect on my ds918, everything went good!
all i want to know is how to keep it always running, such as after reboot the ds918.
thankx!!

**Comment by eizedev** [comment]
Hi @ycj1989 
the AirConnect-Synology package should start automatically during startup of your NAS. 
So in general, any package that was started before the reboot should also be started after the reboot.

Could you please check the logfiles from airconnect? (documented [here](https://github.com/eizedev/AirConnect-Synology#logfiles)). Perhaps we will find additional information there. you can also upload the logfile (or parts of it) here.
