### ISSUE TITLE
can't run AirConnect on Synology 

### ISSUE THREAD

**Issue by xDimiXx** [eizedev/AirConnect-Synology#69]
I tried to install the packages AirConnect-dsm7-arm-1.0.13-20221216.spk or even AirConnect-dsm7-arm-static-1.0.13-20221216.spk on my Synology 218j with DSM 7.0-41890. The installation is fine but the app does not start. Maybe I use a wrong package?

Thanks and BR

**Comment by eizedev** [comment]
Hey @xDimiXx 
sorry, I missed your issue. The arm package (or arm-static) is the correct one for your hardware.
We had several problems related to older Synology NAS devices and the new AirConnect packages from `1.0` and newer releases. You could find a lot of information in this thread: https://github.com/eizedev/AirConnect-Synology/issues/63#issuecomment-1382176635 .
You could stay at [0.2.51.2](https://github.com/eizedev/AirConnect-Synology/releases/tag/0.2.51.2-20220206) if nothing will help.

i have also released a new version, you could also try this version: https://github.com/eizedev/AirConnect-Synology/releases/tag/1.1.0-20230423
