### ISSUE TITLE
Limit to Non-AirPlay2 enabled Sonos Models

### ISSUE THREAD

**Issue by nathangoodman** [eizedev/AirConnect-Synology#7]
Thank you for your work packaging this up for Synology.  You made it dead simple to setup and get working out of the box.

Im wondering if its possible to configure the package to start with the `./airupnp -o S1,S3,S5,S9,S12,ZP80,ZP90,S15,ZP100,ZP120` option to remove all of the Sonos that already have the AirPlay 2 enabled?

**Comment by nathangoodman** [comment]
I ended up just creating my own Docker container with this running with the -o flag.

**Comment by eizedev** [comment]
Hi @nathangoodman 
thanks for that, i have tested this to not break existing local config files from users. (config.xml)
I have released a new version where this is now included by default: [0.2.41.0-20201209](https://github.com/eizedev/AirConnect-Synology/releases/tag/0.2.41.0-20201209)

**Comment by nathangoodman** [comment]
This is great.  I've removed my bespoke Docker setup and have just installed this package instead.  Works well.  Thanks again!
