### ISSUE TITLE
Chromecast Volume

### ISSUE THREAD

**Issue by FatFairFoot** [eizedev/AirConnect-Synology#71]
Hello,

I just have a little issue with the volume, each time the cast begin the volume is low.
Maybe I'm missing something ?

I see this when the stream starts : 

[17:06:15.188453] handle_rtsp:363 [0x7f2ba4013fd0]: received SET_PARAMETER
[17:06:15.188475] handle_rtsp:528 [0x7f2ba4013fd0]: SET PARAMETER volume -20.000000
[17:06:15.188489] CastSetDeviceVolume:299 [0x1150ac0]: Queuing SET_VOLUME
**[17:06:15.188499] raop_cb:227 [0x1150ac0]: Volume[0..1] 0.3333**
[17:06:15.188575] handle_rtsp:562 [0x7f2ba4013fd0]: responding:
RTSP/1.0 200 OK
Audio-Jack-Status: connected; type=analog
CSeq: 7

So, I generated a config file for aircast and set <media_volume>1</media_volume>, because I saw that this could help but nothing changes.
(Seeing in the logs that "[17:04:11.321656] main:891 no config file, using defaults" not displaying anymore so the confilg file seems to be processed)

Target devices are Nest Hubs and Nest Audios.

Could you help me with this ?

Thanks !!!

**Comment by eizedev** [comment]
hi @FatFairFoot 

could you please post your issue/question at the [official AirConnect repository](https://github.com/philippe44/AirConnect/issues)? Thanks
Your problem could be related to an issue with airupnp/aircast and is not related to the Synology AirConnect package.

i will also update to `1.1.0` in the next days, but the changelog does not relate to any fixed error that is related to your problem.

**Comment by FatFairFoot** [comment]
ok I will ! Thanks ;-)

**Comment by eizedev** [comment]
@FatFairFoot 
I have just released a new version that also includes `AirConnect 1.1.0`: https://github.com/eizedev/AirConnect-Synology/releases/tag/1.1.0-20230423
The changelog of `1.1.0` does not relate to any fixed error that is related to your problem, but perhaps you give it a try.
