### ISSUE TITLE
Failed to start AirConnect on DS 918+

### ISSUE THREAD

**Issue by flyingfan76** [eizedev/AirConnect-Synology#8]
Hi, 

It was worked in the past. But all of sudden, the functionality corrupted. I reinstalled the AirConnect but never got it work again.

Here is the error logs taken from the log file.

```log
[08:52:34] Stopping AirConnect ...
[08:53:05] Starting AirConnect ...
[08:53:05] Starting airupnp on 192.168.50.17:49154
[08:53:05.195306] main:1418 Starting airupnp version: v0.2.41.0 (Dec  8 2020 @ 18:43:14)
[08:53:05.195436] main:1426 no config file, using defaults
[08:53:05.197038] Start:1127 Binding to 192.168.50.17:49154
[08:53:05] Starting aircast on 192.168.50.17
[08:53:05.203359] main:958 Starting aircast version: v0.2.41.0 (Dec  8 2020 @ 18:41:57)
[08:53:05.203486] main:966 no config file, using defaults
[08:53:05.203813] Start:716 Binding to 192.168.50.17
[08:53:05] Searching if renderer were added (for 10 seconds)...
[08:53:08.368454] XMLGetFirstDocumentItem:1438 (BUG) ixmlNode_getFirstChild(tmpNode) returned NULL
[08:53:10.372653] XMLGetFirstDocumentItem:1438 (BUG) ixmlNode_getFirstChild(tmpNode) returned NULL
[08:53:15] Failed to start AirConnect on ip "192.168.50.17", stopping it...
[08:53:26] Failed to start AirConnect on any of the local interfaces, please make sure you have at least one UPnP/Sonos/Chromecast device on your network
[08:53:26] Stopping AirConnect ..
```

Is there any configuration issue?
Thanks,

**Comment by eizedev** [comment]
Hi, In the last version i have included the `-o` parameter of airupnp to exclude the Sonos Speakers that already natively support AirPlay. So in general, for the Sonos speakers that natively support AirPlay you do not need AirConnect (airupnp).

Which speaker are you using? (UPNP)

So in general the exclude mentioned above that should not be a problem if you are using other speakers in your environment.
For more information please check the [how it works](https://github.com/eizedev/AirConnect-Synology#how-it-works) of the readme or the changelog on the [latest release](https://github.com/eizedev/AirConnect-Synology/releases/tag/0.2.41.0-20201209).

> [08:53:08.368454] XMLGetFirstDocumentItem:1438 (BUG) ixmlNode_getFirstChild(tmpNode) returned NULL

This error is strange and should not occur. I will release a new version later on for AirConnect 0.2.42.2, perhaps this version is working for you again, a few bugs getting fixed.

**Comment by eizedev** [comment]
Hi again, new release is online: https://github.com/eizedev/AirConnect-Synology/releases/tag/0.2.42.1-20201216

**Comment by flyingfan76** [comment]
Hi, 
Sorry to answer late. The package I used was AirConnect-x86-64-0.2.41.0-20201209.spk.  And I haven't had a chance to test the 1216 package. Will try it out and back to you with my findings.  

Btw the speaker is one Chinese branding (Xiaoai which comes from Xiaomi). 

Thanks,

**Comment by flyingfan76** [comment]
Even with the latest version of 1216, it does not work. SonoAir cannot detect the devices either. I suspect it is the issue of the wireless soundbox. Please close this issue by now.

**Comment by eizedev** [comment]
> Btw the speaker is one Chinese branding (Xiaoai which comes from Xiaomi).

Are you using this Xiamoi speaker exclusively? (So no Sonos etc.) Which one is that exactly?

**Comment by eizedev** [comment]
@flyingfan76 to make it more clear. In my latest two releases i changed the way that AirConnect discovers new DLNA/UPNP Speakers. So only specific models will be discovered, so that all speakers that natively supports airplay will not be discovered and shown in the AirPlay menu anymore. 
So if you tell me the model or at least the name of the xiaomi speaker, i can include this model als well if it not natively supports airplay.

**Comment by flyingfan76** [comment]
@eizedev, thank you for the clarification. I don't know what exactly the model name of xiaomi speaker in english. Maybe it is "xiaoai". Anyway, I will try the new version 20201229 and see if it can help.

**Comment by eizedev** [comment]
> @eizedev, thank you for the clarification. I don't know what exactly the model name of xiaomi speaker in english. Maybe it is "xiaoai". Anyway, I will try the new version 20201229 and see if it can help.

As mentioned in this deep dive post [here](https://www.programmersought.com/article/94913733704/), the model number should be `S12` which is already included in the last two packages. 
Perhaps you could check the model number on your device?
You can find the model number in the upnp device.xml file directly on your speaker, it should be port 9999 when accessing your device in your browser via the IP of your speaker (Example: `http://192.168.1.168:9999`)

![image](https://user-images.githubusercontent.com/6794362/103512401-e6c27100-4e68-11eb-81fa-a79dc6fa4367.png)

You can also find the model number with other tools, too. If using windows, you could open the Explorer, click on Network and the right click on your xiaoai speaker -> Properties. 
Example (german language): 
![image](https://user-images.githubusercontent.com/6794362/103512898-db237a00-4e69-11eb-9781-4b9618cea3fd.png)

**Comment by flyingfan76** [comment]
@eizedev , I tried the latest version. Although it was still not able to find Xiao ai, it really detect the other wireless speaker which was not detected in the past. And for the Xiaoai speaker I used, the model is "S12".

**Comment by flyingfan76** [comment]
@eizedev , a quickly update. After exploring the setting of associated app of xiao ai speaker. I notify the default dlna options has been turned off. After turn it on, xiao ai speaker can be found as well. Really appreciate your patient.  Thx, it is all set now.

**Comment by eizedev** [comment]
Great, I am glad that it works now.

**Comment by eizedev** [comment]
closed due to anser https://github.com/eizedev/AirConnect-Synology/issues/8#issuecomment-755899731
