### ISSUE TITLE
Just to let you know I've removed the bin/ directory and replaced it with a .zip containing all files

### ISSUE THREAD

**Issue by philippe44** [eizedev/AirConnect-Synology#83]
I assume you're using the release artefacts, but just in case...

**Comment by eizedev** [comment]
Hi @philippe44 

Thanks for the info. Currently i am using the commit sha1 reference to get the latest binary for each architecture during the build process in the makefile, f.e.

```bash
curl -s -L https://github.com/philippe44/AirConnect/raw/${REPO_REVISION}/bin/airupnp-linux-${ARCH} -o target/airupnp
chmod +x target/airupnp
curl -s -L https://github.com/philippe44/AirConnect/raw/${REPO_REVISION}/bin/aircast-linux-${ARCH} -o target/aircast
chmod +x target/aircast
```

So I need to change that to download the zip file, extract it, look for any binary file matching the arch and delete everything afterwards. I think i will switch to github actions then.

Any chance to include the binary files in the releases additionally to the zip? So i do not need the download the whole zip.

**Comment by eizedev** [comment]
@philippe44 I have integrated an automated way that downloads the 'latest' zip file or the zip file specified with a version tag with your versioning. If you keep creating releases and tags with a zip file named 'AirConnect-<version>.zip' with this semantic versioning (Major.Minor.Patch - 1.7.0) it will automatically grab the release, downloads the zip, extracts all binaries and use the binaries for bulding the packages for all different architectures of synology devices.
